-- full overview of dataset
use bikes_projects;
Select * from bikestore;


-- there is column called 'MyUnknownColumn', we want to change that and to be named 'month'
Alter table bikestore
Rename column MyUnknownColumn to month;


-- we want to see the count of entries for each column?
Select sum(revenue) as total_revenue, sum(total_units) as total_units_sold, 
       count(distinct order_id) as orders, count(distinct customers) as customers,
       count(distinct sales_rep) as salesreps
from bikestore;


Select count(distinct city) as cities, count(distinct state) as states,
       count(distinct product_name) as products, count(distinct category_name) as categories,
       count(distinct brand_name) as brands, count(distinct store_name) as stores
From bikestore;



-- total revenue generted in each year?
Select year, sum(revenue) as total_revenue
from bikestore
group by year
order by total_revenue desc;



-- total revenue generated in each month?
Select month, sum(revenue) as total_revenue, sum(total_units) as unit_sold
from bikestore
group by month
order by total_revenue desc;


-- sales activity according to the seasons of the year?
-- we will be using the case function here.
Select 
	 Case
         When month In ('Jan' , 'Feb' , 'Mar' ) then 'Winter'
         When month In ('Apr' , 'May' , 'Jun' ) then 'Spring'
         When month In ('Jul' , 'Aug' , 'Sep' ) then 'Summer'
         Else 'Autumn'
	 End as season,
     Sum(revenue) as total_revenue,
     sum(total_units) as total_units_sold
From bikestore
group by season
order by total_revenue desc;



-- total revenue generated in each store?
Select store_name, sum(revenue) as total_revenue, sum(total_units) as unit_sold
from bikestore
group by store_name
order by total_revenue desc;


-- total revenue generated in each city and the state they belong?
Select city, state, sum(revenue) as total_revenue, sum(total_units) as unit_sold 
from bikestore
group by city, state
order by total_revenue desc
limit 10;


-- total revenue generated in each product category?
Select category_name,  sum(revenue) as total_revenue, sum(total_units) as unit_sold
from bikestore
group by category_name
order by total_revenue desc;


-- total revenue generated by each brand category?
Select brand_name,  sum(revenue) as total_revenue, sum(total_units) as unit_sold
from bikestore
group by brand_name
order by total_revenue desc;